# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='阅览量'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='icon_color',
            field=models.CharField(choices=[('primary', '基本-蓝色'), ('success', '成功-绿色'), ('info', '信息-天蓝色'), ('warning', '警告-橙色'), ('danger', '危险-红色')], default='info', max_length=20, verbose_name='图标颜色'),
        ),
    ]
